import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { formatDateTime, passengerFullName, statusTone } from "@/lib/format";
import { getTicketByNumber } from "@/lib/flight-data";

export const dynamic = "force-dynamic";

type VerifyPageProps = {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

function stringParam(params: Record<string, string | string[] | undefined>, key: string) {
  const value = params[key];
  return Array.isArray(value) ? value[0] ?? "" : value ?? "";
}

export default async function VerifyPage({ searchParams }: VerifyPageProps) {
  const params = (await searchParams) ?? {};
  const ticketQuery = stringParam(params, "ticket").trim().toUpperCase();
  const bundle = ticketQuery ? await getTicketByNumber(ticketQuery) : null;

  return (
    <main className="min-h-screen bg-white">
      <SiteHeader />
      <section className="bg-white px-4 py-16 text-slate-900 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl">
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-[#1565c0]">Ticket verification</p>
          <h1 className="mt-3 text-5xl font-semibold">Verify a ticket</h1>
          <p className="mt-4 max-w-2xl text-slate-600">
            Enter a ticket number. Plane Finder only returns valid results when Ticket → Booking → Flight exists.
          </p>
          <form action="/verify" method="get" className="mt-8 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 text-slate-900 shadow-sm sm:flex-row">
            <input name="ticket" defaultValue={ticketQuery} placeholder="PF-2026-ABCDEFGH" className="min-w-0 flex-1 rounded-md border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-[#1565c0]/20" />
            <button className="rounded-md bg-[#1565c0] px-6 py-3 font-semibold text-white" type="submit">Verify</button>
          </form>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        {!ticketQuery ? (
          <div className="rounded-[2rem] bg-white p-8 shadow-xl ring-1 ring-slate-200">
            <h2 className="text-2xl font-black text-slate-950">Awaiting ticket number</h2>
            <p className="mt-2 text-slate-600">Use a ticket number generated by a completed booking.</p>
          </div>
        ) : bundle ? (
          <div className="rounded-[2rem] bg-white p-8 shadow-xl ring-1 ring-slate-200">
            <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
              <div>
                <p className="text-sm font-black uppercase tracking-[0.22em] text-emerald-600">Database match found</p>
                <h2 className="mt-2 text-3xl font-black text-slate-950">Ticket is {bundle.ticket.status}</h2>
                <p className="mt-2 text-slate-600">Verified against booking reference {bundle.booking.bookingReference}.</p>
              </div>
              <span className={`rounded-full px-4 py-2 text-sm font-black ring-1 ${statusTone(bundle.ticket.status)}`}>{bundle.ticket.status}</span>
            </div>
            <div className="mt-7 grid gap-4 md:grid-cols-2">
              {[
                ["Passenger", passengerFullName(bundle.passengers[0]?.firstName, bundle.passengers[0]?.lastName)],
                ["Ticket number", bundle.ticket.ticketNumber],
                ["Flight", bundle.flight.flightNumber],
                ["Route", `${bundle.flight.origin} → ${bundle.flight.destination}`],
                ["Departure", formatDateTime(bundle.flight.departureTime)],
                ["Seat", bundle.ticket.seat],
              ].map(([label, value]) => (
                <div key={label} className="rounded-2xl bg-slate-50 p-4">
                  <p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">{label}</p>
                  <p className="mt-1 font-black text-slate-950">{value}</p>
                </div>
              ))}
            </div>
            <Link href={`/ticket/${bundle.ticket.ticketNumber}`} className="mt-7 inline-flex rounded-2xl bg-slate-950 px-6 py-3 font-black text-white">Open online ticket</Link>
          </div>
        ) : (
          <div className="rounded-[2rem] border border-red-200 bg-red-50 p-8 shadow-xl">
            <p className="text-sm font-black uppercase tracking-[0.22em] text-red-600">Not found</p>
            <h2 className="mt-2 text-3xl font-black text-red-950">Ticket not found.</h2>
            <p className="mt-2 text-red-800">This ticket number does not match a real ticket record in the backend database.</p>
          </div>
        )}
      </section>
    </main>
  );
}
